#!/usr/bin/env bash

if [[ $# == 0 ]]; then
    echo 'No arguments given; usage: install <packages>'
    exit 1
fi

if ! command -v brew >/dev/null 2>&1; then
    echo 'brew not found, exiting'
    exit 1
fi

ghostty_install() {
    echo 'Installing ghostty'
    brew install ghostty
    echo "Creating ghostty symlinks in $HOME"
    stow ghostty
}

helix_install() {
    echo 'Installing helix'
    brew install evil-helix 
    echo "Creating helix symlinks in $HOME"
    stow helix
}

lazygit_install() {
    echo 'Installing lazygit'
    brew install lazygit

    echo "Creating lazygit symlinks in $HOME"
    stow lazygit
}

nvim_install() {
    echo 'Installing nvim'
    brew install nvim
    echo "Creating nvim symlinks in $HOME"
    stow nvim
}

vim_install() {
    echo 'Installing vim'
    brew install vim
    echo "Creating vim symlinks in $HOME"
    stow vim
}

yazi_install() {
    echo 'Installing yazi'
    brew install yazi
    echo "Creating yazi symlinks in $HOME"
    stow yazi
}

zellij_install() {
    echo 'Installing zellij'
    brew install zellij
    echo "Creating zellij symlinks in $HOME"
    stow zellij
}

zsh_install() {
    echo "Creating zsh symlinks in $HOME"
    stow zsh
}

handle_package() {
    local package=$1
    case "$package" in
        ghostty) ghostty_install ;;
        helix) helix_install ;;
        lazygit) lazygit_install ;;
        nvim) nvim_install ;;
        vim) vim_install ;;
        yazi) yazi_install ;;
        zellij) zellij_install ;;
        zsh) zsh_install ;;
        *) echo "Unknown package: $package" ;;
    esac
}

echo 'Installing basic tools'
brew install fd fzf ripgrep stow zoxide

for package in "$@"; do
    handle_package $package
done
