[[language]]
name = "python"
language-servers = ["pyright"]

[[language]]
name = "typescript"
auto-format = true
formatter = { command = "npx", args = ["prettier", "--parser", "typescript"] }
language-servers = ["typescript-language-server", "vscode-eslint-language-server"]

[[language]]
name = "tsx"
auto-format = true
formatter = { command = "npx", args = ["prettier", "--parser", "typescript"] }
language-servers = ["typescript-language-server", "vscode-eslint-language-server"]
